[package]
name = "serde-struct-tuple-enum"
version = "0.1.0"
edition = "2021"
description = "Procedural macro for deserializing an enum of structs from tuples."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "enum", "tuple"]
license = "MIT"

[dependencies]
serde-struct-tuple-enum-proc-macro = { path = "serde-struct-tuple-enum-proc-macro" }
