[package]
name = "serde-struct-tuple-enum"
version = "0.1.1"
edition = "2024"
description = "Procedural macro for deserializing an enum of structs from tuples."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "enum", "tuple"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamp/serde-struct-tuple-enum"

[dependencies]
serde = { workspace = true }

serde-struct-tuple-enum-proc-macro = "0.1.0"

[dev-dependencies]
serde-struct-tuple = { workspace = true }
serde_json = { workspace = true }
