use serde::{
    Deserialize,
    Serialize,
};
use uuid::Uuid;

/// The state of a [`Player`] in a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub enum PlayerState {
    /// The player is not ready to start the battle.
    #[serde(rename = "waiting")]
    Waiting,
    /// The player is ready to start the battle.
    #[serde(rename = "ready")]
    Ready,
}

/// The result of a validating a [`Player`] in a [`Battle`].
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct PlayerValidation {
    /// Problems generated by validation.
    pub problems: Vec<String>,
}

/// A player in a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct Player {
    /// The unique identifier of the player, used for all interactions made by the player.
    pub id: String,
    /// Name of the player.
    pub name: String,
    /// The state of the player.
    pub state: PlayerState,
}

/// A side in a [`Battle`].
///
/// A side is made up of one or more [`Player`]s.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct Side {
    /// Name of the side.
    pub name: String,
    /// Players on the side.
    pub players: Vec<Player>,
}

/// The state of a [`Battle`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub enum BattleState {
    /// The battle is being prepared.
    #[serde(rename = "preparing")]
    Preparing,
    /// The battle is active and ongoing.
    #[serde(rename = "active")]
    Active,
    /// The battle ended.
    #[serde(rename = "finished")]
    Finished,
}

/// The status of a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct BattleStatus {
    /// The current turn number.
    pub turn: u64,
}

/// Metadata about a battle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct BattleMetadata {
    /// Player who created the battle.
    pub creator: String,
    /// The type of the battle format.
    pub battle_type: battler::battle::BattleType,
    /// The rules of the battle.
    pub rules: Vec<String>,
}

/// A battle.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct Battle {
    /// The unique identifier of the battle, used for all interactions made by players.
    #[serde(with = "uuid::serde::simple")]
    #[cfg_attr(feature = "typescript", ts(as = "String"))]
    pub uuid: Uuid,
    /// The state of the battle.
    pub state: BattleState,
    /// The status of the battle.
    pub status: BattleStatus,
    /// The sides participating in the battle.
    pub sides: Vec<Side>,
    /// The error that occurred when continuing the battle.
    pub error: Option<String>,
    /// Metadata about the battle.
    pub metadata: BattleMetadata,
}

/// A preview of a [`Player`] in a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct PlayerPreview {
    /// The unique identifier of the player.
    pub id: String,
    /// Name of the player.
    pub name: String,
}

/// A preview of a [`Side`] in a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct SidePreview {
    /// Players on the side.
    pub players: Vec<PlayerPreview>,
}

/// A preview of a [`Battle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "typescript", derive(ts_rs::TS))]
#[cfg_attr(feature = "typescript", ts(export))]
pub struct BattlePreview {
    /// The unique identifier of the battle.
    #[serde(with = "uuid::serde::simple")]
    #[cfg_attr(feature = "typescript", ts(as = "String"))]
    pub uuid: Uuid,
    /// The sides participating in the battle.
    pub sides: Vec<SidePreview>,
}
