[package]
name = "battler-wamp-values"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
battler-wamp-values-proc-macro = { path = "battler-wamp-values-proc-macro" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.65"
