[package]
name = "serde-struct-tuple-enum-proc-macro"
version = "0.1.0"
edition = "2024"
description = "Procedural macro for deserializing an enum of structs from tuples."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "enum", "tuple"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
itertools = "0.13.0"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", default-features = false }
syn = "2.0"
