[package]
name = "battler-wamprat-message"
version = "0.1.3"
edition = "2024"
description = "Procedural macro for sending structs over WAMP messages."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket", "message"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamprat/battler-wamprat-message"

[dependencies]
battler-wamp-values = { workspace = true }
thiserror = { workspace = true }

battler-wamprat-message-proc-macro = "0.1.2"
