[package]
name = "battler-wamprat-message"
version = "0.1.0"
edition = "2024"
description = "Procedural macro for sending structs over WAMP messages."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket", "message"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamprat/battler-wamprat-message"

[dependencies]
battler-wamp-values = "0.1"
battler-wamprat-message-proc-macro = "0.1.0"
thiserror = "1.0.65"
