[package]
name = "battler-wamprat-error-proc-macro"
version = "0.1.2"
edition = "2024"
description = "Procedural macro for custom WAMP errors."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket", "error"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamprat/battler-wamprat-error/battler-wamprat-error-proc-macro"

[lib]
proc-macro = true

[dependencies]
battler-wamp = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }

battler-wamprat-error = { path = ".." }
