[package]
name = "serde-struct-tuple"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
serde-struct-tuple-proc-macro = { path = "serde-struct-tuple-proc-macro" }
