[package]
name = "serde-struct-tuple"
version = "0.1.0"
edition = "2021"
description = "Procedural macro for deserializing a struct from a tuple of its fields."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "tuple"]
license = "MIT"

[dependencies]
serde = { version = "1.0", default-features = false }
serde-struct-tuple-proc-macro = { path = "serde-struct-tuple-proc-macro" }
