[package]
name = "serde-struct-tuple"
version = "0.1.3"
edition = "2024"
description = "Procedural macro for deserializing a struct from a tuple of its fields."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "tuple"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamp/serde-struct-tuple"

[dependencies]
serde = "1.0"
serde-struct-tuple-proc-macro = "0.1.2"

[dev-dependencies]
serde_json = "1.0"
