import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const bindingsSrcDir = path.resolve(__dirname, "bindings");
const bindingsDestDir = path.resolve(__dirname, "pkg", "node", "bindings");
const dtsPath = path.resolve(__dirname, "pkg", "node", "battler_state.d.ts");
const pkgJsonPath = path.resolve(__dirname, "pkg", "node", "package.json");

// 1. Regenerate TS bindings from Rust types
console.log("Generating TypeScript bindings via cargo test...");
execSync("cargo test -p battler-state --features typescript export_types", {
  cwd: __dirname,
  stdio: "inherit",
});

// 2. Copy bindings directory if it exists
if (fs.existsSync(bindingsSrcDir)) {
  fs.cpSync(bindingsSrcDir, bindingsDestDir, { recursive: true });
}

// 3. Scan the copied bindings directory
if (fs.existsSync(bindingsDestDir)) {
  const files = fs.readdirSync(bindingsDestDir);
  const reExports = files
    .filter((f) => f.endsWith(".ts"))
    .map((f) => {
      const name = path.basename(f, ".ts");
      return `export type { ${name} } from "./bindings/${name}.js";`;
    })
    .join("\n");

  // 4. Append to battler_state.d.ts
  if (fs.existsSync(dtsPath)) {
    let dtsContent = fs.readFileSync(dtsPath, "utf8");
    const separator = "\n// -- AUTOGENERATED BINDINGS RE-EXPORTS --\n";
    const parts = dtsContent.split(separator);

    dtsContent = parts[0] + separator + reExports + "\n";
    fs.writeFileSync(dtsPath, dtsContent, "utf8");
  }
}

// 5. Compile state_selectors.ts to the pkg/node output directory
console.log("Compiling state_selectors.ts to pkg/node...");
execSync("npx tsc -p ../js/tsconfig.json", { cwd: path.resolve(__dirname, "js-tests") });

// 6. Update pkg/node/package.json if necessary to include the bindings directory and state_selectors files
if (fs.existsSync(pkgJsonPath)) {
  const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"));
  let updated = false;
  if (!pkg.files.includes("bindings")) {
    pkg.files.push("bindings");
    updated = true;
  }
  if (!pkg.files.includes("state_selectors.js")) {
    pkg.files.push("state_selectors.js");
    updated = true;
  }
  if (!pkg.files.includes("state_selectors.d.ts")) {
    pkg.files.push("state_selectors.d.ts");
    updated = true;
  }
  if (updated) {
    fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2), "utf8");
  }
}

// 7. Export stateSelectors namespace from the root JavaScript module (CommonJS)
const jsPath = path.resolve(__dirname, "pkg", "node", "battler_state.js");
if (fs.existsSync(jsPath)) {
  let jsContent = fs.readFileSync(jsPath, "utf8");
  const jsExportMarker = "\n// -- AUTOGENERATED SELECTORS RE-EXPORTS --\n";
  const parts = jsContent.split(jsExportMarker);

  const reExports = 'exports.stateSelectors = require("./state_selectors.js");\n';
  jsContent = parts[0] + jsExportMarker + reExports;
  fs.writeFileSync(jsPath, jsContent, "utf8");
}

// 8. Re-export stateSelectors namespace from the root declaration file (.d.ts)
if (fs.existsSync(dtsPath)) {
  let dtsContent = fs.readFileSync(dtsPath, "utf8");
  const dtsExportMarker = "\n// -- AUTOGENERATED SELECTORS TYPE RE-EXPORTS --\n";
  const parts = dtsContent.split(dtsExportMarker);

  const dtsExports = 'export * as stateSelectors from "./state_selectors.js";\n';
  dtsContent = parts[0] + dtsExportMarker + dtsExports;
  fs.writeFileSync(dtsPath, dtsContent, "utf8");
}

// 9. Re-link npm workspaces to expose the newly built package and its types
console.log("Re-linking npm workspaces...");
execSync("npm install", { cwd: path.resolve(__dirname, ".."), stdio: "inherit" });
