import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const bindingsSrcDir = path.resolve(__dirname, "bindings");

// 1. Regenerate TS bindings from Rust types
console.log("Generating TypeScript bindings via cargo test...");
execSync("cargo test -p battler-state --features typescript export_types", {
  cwd: __dirname,
  stdio: "inherit",
});

const targets = ["node", "bundler"];

// 2. Copy bindings and update dts re-exports for all target packages
for (const target of targets) {
  const targetDir = path.resolve(__dirname, "pkg", target);
  if (!fs.existsSync(targetDir)) continue;

  const bindingsDestDir = path.resolve(targetDir, "bindings");
  const dtsPath = path.resolve(targetDir, "battler_state.d.ts");

  if (fs.existsSync(bindingsSrcDir)) {
    if (fs.existsSync(bindingsDestDir)) {
      fs.rmSync(bindingsDestDir, { recursive: true, force: true });
    }
    fs.mkdirSync(bindingsDestDir, { recursive: true });
    const files = fs.readdirSync(bindingsSrcDir);
    for (const f of files) {
      if (f.endsWith(".ts")) {
        const name = path.basename(f, ".ts");
        fs.copyFileSync(
          path.resolve(bindingsSrcDir, f),
          path.resolve(bindingsDestDir, `${name}.d.ts`),
        );
      }
    }
  }

  if (fs.existsSync(bindingsDestDir)) {
    const files = fs.readdirSync(bindingsDestDir);
    const reExports = files
      .filter((f) => f.endsWith(".d.ts"))
      .map((f) => {
        const name = path.basename(f, ".d.ts");
        return `export type { ${name} } from "./bindings/${name}.js";`;
      })
      .join("\n");

    if (fs.existsSync(dtsPath)) {
      let dtsContent = fs.readFileSync(dtsPath, "utf8");
      const separator = "\n// -- AUTOGENERATED BINDINGS RE-EXPORTS --\n";
      const parts = dtsContent.split(separator);
      dtsContent = parts[0] + separator + reExports + "\n";
      fs.writeFileSync(dtsPath, dtsContent, "utf8");
    }
  }
}

// 3. Compile state_selectors.ts to pkg/node (CommonJS) and pkg/bundler (ESNext)
console.log("Compiling state_selectors.ts for Node (CommonJS) and Bundler (ESNext)...");
execSync("npx tsc -p ../js/tsconfig.json --outDir ../pkg/node --module CommonJS", {
  cwd: path.resolve(__dirname, "js-tests"),
});
if (fs.existsSync(path.resolve(__dirname, "pkg", "bundler"))) {
  execSync(
    "npx tsc -p ../js/tsconfig.json --outDir ../pkg/bundler --module ESNext --moduleResolution bundler",
    { cwd: path.resolve(__dirname, "js-tests") },
  );
}

// 4. Finalize files and re-exports in target directories
for (const target of targets) {
  const targetDir = path.resolve(__dirname, "pkg", target);
  if (!fs.existsSync(targetDir)) continue;

  const dtsPath = path.resolve(targetDir, "battler_state.d.ts");
  const pkgJsonPath = path.resolve(targetDir, "package.json");
  const jsPath = path.resolve(targetDir, "battler_state.js");

  // Update package.json
  if (fs.existsSync(pkgJsonPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"));
    let updated = false;
    if (!pkg.files.includes("bindings")) {
      pkg.files.push("bindings");
      updated = true;
    }
    if (!pkg.files.includes("state_selectors.js")) {
      pkg.files.push("state_selectors.js");
      updated = true;
    }
    if (!pkg.files.includes("state_selectors.d.ts")) {
      pkg.files.push("state_selectors.d.ts");
      updated = true;
    }
    if (updated) {
      fs.writeFileSync(pkgJsonPath, JSON.stringify(pkg, null, 2), "utf8");
    }
  }

  // Re-export stateSelectors in JS module
  if (fs.existsSync(jsPath)) {
    let jsContent = fs.readFileSync(jsPath, "utf8");
    const jsExportMarker = "\n// -- AUTOGENERATED SELECTORS RE-EXPORTS --\n";
    const parts = jsContent.split(jsExportMarker);

    const reExports =
      target === "node"
        ? 'exports.stateSelectors = require("./state_selectors.js");\n'
        : 'export * as stateSelectors from "./state_selectors.js";\n';
    jsContent = parts[0] + jsExportMarker + reExports;
    fs.writeFileSync(jsPath, jsContent, "utf8");
  }

  // Re-export stateSelectors in .d.ts
  if (fs.existsSync(dtsPath)) {
    let dtsContent = fs.readFileSync(dtsPath, "utf8");
    const dtsExportMarker = "\n// -- AUTOGENERATED SELECTORS TYPE RE-EXPORTS --\n";
    const parts = dtsContent.split(dtsExportMarker);

    const dtsExports = 'export * as stateSelectors from "./state_selectors.js";\n';
    dtsContent = parts[0] + dtsExportMarker + dtsExports;
    fs.writeFileSync(dtsPath, dtsContent, "utf8");
  }
}

if (!process.env.npm_lifecycle_event) {
  console.log("Re-linking npm workspaces...");
  execSync("npm install", { cwd: path.resolve(__dirname, ".."), stdio: "inherit" });
} else {
  console.log("Skipping npm install in post-build (already running inside npm lifecycle event).");
}
