[package]
name = "serde-struct-tuple-proc-macro"
version = "0.1.0"
edition = "2021"
description = "Procedural macro for deserializing a struct from a tuple of its fields."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "tuple"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", default-features = false }
syn = "2.0"
