[package]
name = "serde-struct-tuple-proc-macro"
version = "0.1.2"
edition = "2024"
description = "Procedural macro for deserializing a struct from a tuple of its fields."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["serde", "struct", "tuple"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamp/serde-struct-tuple/serde-struct-tuple-proc-macro"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
