use std::{
    fmt::Display,
    num::ParseIntError,
    str::FromStr,
};

use battler_wamp_values::{
    Integer,
    WampList,
};
use battler_wamprat_message::WampApplicationMessage;
use battler_wamprat_schema::WampSchema;
use battler_wamprat_uri::WampUriMatcher;

/// An active battle.
#[derive(Debug, Clone, WampList)]
pub struct Battle {
    /// JSON-serialized [`battler_service::Battle`].
    pub battle_json: String,
}

/// A preview of an active battle.
#[derive(Debug, Clone, WampList)]
pub struct BattlePreview {
    /// JSON-serialized [`battler_service::BattlePreview`].
    pub battle_json: String,
}

/// Arguments for listing battles.
#[derive(Debug, Clone, WampList)]
pub struct BattlesInputArgs {
    /// Number of battles.
    pub count: Integer,
    /// Offset.
    pub offset: Integer,
}

/// Input for listing battles.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct BattlesInput(#[arguments] pub BattlesInputArgs);

/// Arguments for the output of listing battles.
#[derive(Debug, Clone, WampList)]
pub struct BattlesOutputArgs {
    /// Battles.
    pub battles: Vec<BattlePreview>,
}

/// Arguments for listing battles for a player.
#[derive(Debug, Clone, WampList)]
pub struct BattlesForPlayerInputArgs {
    /// Player.
    pub player: String,
    /// Number of battles.
    pub count: Integer,
    /// Offset.
    pub offset: Integer,
}
/// Input for listing battles for a player.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct BattlesForPlayerInput(#[arguments] pub BattlesForPlayerInputArgs);

/// Output of listing battles.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct BattlesOutput(#[arguments] pub BattlesOutputArgs);

/// Arguments for creating a new battle.
#[derive(Debug, Clone, WampList)]
pub struct CreateInputArgs {
    /// JSON-serialized [`battler::CoreBattleOptions`].
    pub options_json: String,
    /// JSON-serialized [`battler_service::BattleServiceOptions`].
    pub service_options_json: String,
}

/// Input for creating a new battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct CreateInput(#[arguments] pub CreateInputArgs);

/// An application message around an active battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct BattleOutput(#[arguments] pub Battle);

/// URI pattern for looking up a single battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}")]
pub struct BattlePattern(pub String);

/// Input for looking up a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct BattleInput;

/// URI pattern for updating a player's team in a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.update_team")]
pub struct UpdateTeamPattern(pub String);

/// Arguments for updating a team.
#[derive(Debug, Clone, WampList)]
pub struct UpdateTeamInputArgs {
    /// Player ID.
    pub player: String,
    /// JSON-serialized [`battler::TeamData`].
    pub team_data_json: String,
}

/// Input for updating a team.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct UpdateTeamInput(#[arguments] pub UpdateTeamInputArgs);

/// Output of updating a team.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct UpdateTeamOutput;

/// URI pattern for validating a player in a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.validate_player")]
pub struct ValidatePlayerPattern(pub String);

/// Arguments for validating a player.
#[derive(Debug, Clone, WampList)]
pub struct ValidatePlayerInputArgs {
    /// Player ID.
    pub player: String,
}

/// Input for validating a player.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct ValidatePlayerInput(#[arguments] pub ValidatePlayerInputArgs);

/// Arguments for the output of validating a player in a battle.
#[derive(Debug, Clone, WampList)]
pub struct ValidatePlayerOutputArgs {
    /// Problems generated by validation.
    pub problems: Vec<String>,
}

/// Output of validating a player in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct ValidatePlayerOutput(#[arguments] pub ValidatePlayerOutputArgs);

/// URI pattern for starting a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.start")]
pub struct StartPattern(pub String);

/// Input for starting a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct StartInput;

/// Output of starting a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct StartOutput;

/// URI pattern for reading a player's data in a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.player_data")]
pub struct PlayerDataPattern(pub String);

/// Arguments for reading a player's data in a battle.
#[derive(Debug, Clone, WampList)]
pub struct PlayerDataInputArgs {
    /// Player ID.
    pub player: String,
}

/// Input for reading a player's data in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct PlayerDataInput(#[arguments] pub PlayerDataInputArgs);

/// Arguments for the player's data in a battle.
#[derive(Debug, Clone, WampList)]
pub struct PlayerDataOutputArgs {
    /// JSON-serialized [`battler::PlayerData`].
    pub player_data_json: String,
}

/// A player's data in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct PlayerDataOutput(#[arguments] pub PlayerDataOutputArgs);

/// URI pattern for reading a player's current request in a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.request")]
pub struct RequestPattern(pub String);

/// Arguments for reading a player's current request in a battle.
#[derive(Debug, Clone, WampList)]
pub struct RequestInputArgs {
    /// Player ID.
    pub player: String,
}

/// Input for reading a player's current request in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct RequestInput(#[arguments] pub RequestInputArgs);

/// Arguments for a player's current request in a battle.
#[derive(Debug, Clone, WampList)]
pub struct RequestOutputArgs {
    /// JSON-serialized [`battler::Request`].
    pub request_json: Option<String>,
}

/// A player's current request in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct RequestOutput(#[arguments] pub RequestOutputArgs);

/// URI pattern for a player making a choice in a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.make_choice")]
pub struct MakeChoicePattern(pub String);

/// Arguments for a player making a choice in a battle.
#[derive(Debug, Clone, WampList)]
pub struct MakeChoiceInputArgs {
    /// Player ID.
    pub player: String,
    /// Choice.
    pub choice: String,
}

/// Input for a player making a choice in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct MakeChoiceInput(#[arguments] pub MakeChoiceInputArgs);

/// Output of a player making a choice in a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct MakeChoiceOutput;

/// URI pattern for deleting a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.delete")]
pub struct DeletePattern(pub String);

/// Input for deleting a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct DeleteInput;

/// Output of deleting a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct DeleteOutput;

/// URI pattern for reading the full log of a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.full_log")]
pub struct FullLogPattern(pub String);

/// Arguments for reading the full log of a battle.
#[derive(Debug, Clone, WampList)]
pub struct FullLogInputArgs {
    /// Side of the battle.
    ///
    /// If `None`, the public log is used.
    pub side: Option<u64>,
}

/// Input for reading the full log of a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct FullLogInput(#[arguments] pub FullLogInputArgs);

/// Arguments for the full log of a battle.
#[derive(Debug, Clone, WampList)]
pub struct FullLogOutputArgs {
    pub log: Vec<String>,
}

/// The full log of a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct FullLogOutput(#[arguments] pub FullLogOutputArgs);

/// URI pattern for reading the last log entry of a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.last_log_entry")]
pub struct LastLogEntryPattern(pub String);

/// Arguments for reading the last log entry of a battle.
#[derive(Debug, Clone, WampList)]
pub struct LastLogEntryInputArgs {
    /// Side of the battle.
    ///
    /// If `None`, the public log is used.
    pub side: Option<u64>,
}

/// Input for reading the last log entry of a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct LastLogEntryInput(#[arguments] pub LastLogEntryInputArgs);

/// Output of reading the last log entry of a battle.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct LastLogEntryOutput(#[arguments] pub Option<LogEntry>);

#[derive(Debug, Default, Clone)]
pub enum LogSelector {
    #[default]
    Public,
    Side(usize),
}

impl FromStr for LogSelector {
    type Err = ParseIntError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s == "public" {
            Ok(Self::Public)
        } else {
            s.parse().map(|val| Self::Side(val))
        }
    }
}

impl Display for LogSelector {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Public => write!(f, "public"),
            Self::Side(val) => write!(f, "{val}"),
        }
    }
}

/// URI pattern for reading the log of a battle.
#[derive(Debug, Clone, WampUriMatcher)]
#[uri("com.battler.battler_service.battles.{0}.log.{1}")]
pub struct LogPattern(pub String, pub LogSelector);

/// A log entry.
#[derive(Debug, Clone, WampList)]
pub struct LogEntry {
    /// Index of the entry.
    pub index: Integer,
    /// Content of the entry.
    pub content: String,
}

/// An event for a new log entry.
#[derive(Debug, Clone, WampApplicationMessage)]
pub struct LogEvent(#[arguments] pub LogEntry);

/// Service for managing battles on the `battler` battle engine.
#[derive(Debug, Clone, WampSchema)]
#[realm("com.battler")]
pub enum BattlerService {
    /// Creates a new battle.
    #[rpc(uri = "com.battler.battler_service.battles.create", input = CreateInput, output = BattleOutput)]
    Create,
    /// Lists battles.
    #[rpc(uri = "com.battler.battler_service.battles", input = BattlesInput, output = BattlesOutput)]
    Battles,
    /// Lists battles for a player.
    #[rpc(uri = "com.battler.battler_service.battles_for_player", input = BattlesForPlayerInput, output = BattlesOutput)]
    BattlesForPlayer,
    /// Looks up an active battle.
    #[rpc(pattern = BattlePattern, input = BattleInput, output = BattleOutput)]
    Battle,
    /// Updates a player's team in a battle.
    #[rpc(pattern = UpdateTeamPattern, input = UpdateTeamInput, output = UpdateTeamOutput)]
    UpdateTeam,
    /// Validates a player in a battle.
    #[rpc(pattern = ValidatePlayerPattern, input = ValidatePlayerInput, output = ValidatePlayerOutput)]
    ValidatePlayer,
    /// Starts a battle.
    #[rpc(pattern = StartPattern, input = StartInput, output = StartOutput)]
    Start,
    /// Reads a player's data in a battle.
    #[rpc(pattern = PlayerDataPattern, input = PlayerDataInput, output = PlayerDataOutput)]
    PlayerData,
    /// Reads a player's current request in a battle.
    #[rpc(pattern = RequestPattern, input = RequestInput, output = RequestOutput)]
    Request,
    /// Makes a choice for a player in a battle.
    #[rpc(pattern = MakeChoicePattern, input = MakeChoiceInput, output = MakeChoiceOutput)]
    MakeChoice,
    /// Deletes a battle.
    #[rpc(pattern = DeletePattern, input = DeleteInput, output = DeleteOutput)]
    Delete,
    /// Reads the full log of a battle.
    #[rpc(pattern = FullLogPattern, input = FullLogInput, output = FullLogOutput)]
    FullLog,
    /// Reads the last log entry of a battle.
    #[rpc(pattern = LastLogEntryPattern, input = LastLogEntryInput, output = LastLogEntryOutput)]
    LastLogEntry,
    /// Events for new entries to the log of a battle.
    #[pubsub(pattern = LogPattern, subscription = LogPattern, event = LogEvent)]
    Log,
}
