name: Set up Rust

runs:
  using: "composite"
  steps:
    - name: Install Rust nightly
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: nextest
