[package]
name = "battler-wamp-values-proc-macro"
version = "0.2.0"
edition = "2024"
description = "Procedural macros for WAMP serialization."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamp/battler-wamp-values/battler-wamp-values-proc-macro"

[lib]
proc-macro = true

[dependencies]
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }

battler-wamp-values = { path = ".." }