[package]
name = "battler-wamp-values-proc-macro"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for WAMP serialization."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamp/battler-wamp-values/battler-wamp-values-proc-macro"

[lib]
proc-macro = true

[dependencies]
itertools = "0.13.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
assert_matches = "1.5.0"
battler-wamp-values = { path = ".." }
pretty_assertions = "1.4.0"
