name: Deploy Web App to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Vercel
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Build WASM and TS Bindings
        uses: ./.github/actions/build-wasm-and-bindings

      - name: Build Web App Dependencies
        run: npm run build:web-app-deps

      - name: Build battler-web-app
        run: npm run build:web-app
        env:
          VITE_SERVER_URL: "ws.battler.live"
          VITE_BUG_REPORT_API_URL: "https://bugs.battler.live/api/report-bug"

      - name: Deploy to Vercel
        run: |
          cp js-clients/battler-web-app/vercel.json js-clients/battler-web-app/dist/vercel.json
          npx --yes vercel deploy --cwd js-clients/battler-web-app/dist --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

