name: js-clients

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GEMINI_PYTHON_VENV: ${{ github.workspace }}/.venv

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      run_js_clients: ${{ steps.detector.outputs.run_js_clients }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect Changes
        uses: ./.github/actions/detect-changes
        id: detector

  test-js-clients:
    name: Run JS/WAMP Integration Tests
    needs: detect-changes
    if: github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.run_js_clients == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build WASM and TS Bindings
        uses: ./.github/actions/build-wasm-and-bindings
      - name: Build JS Client Workspaces
        run: npm run build:js-clients
      - name: Build Rust server binary
        run: cargo build --bin battler-server
      - name: Run JS client integration tests
        run: npm run test:js-clients
